name: Eleventy Build
on: workflow_dispatch

jobs:
  build_deployftp:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.1
        with:
         args: --output _dist
         install_dependencies: true
      - name: deployftp
        uses: AbleLincoln/push-to-sftp@v1.0
        with:
          host: ${{ secrets.FTP_SERVER }}
          port: 22
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
          server-dir: ./lamp0/web/vhosts/crm.6337.fr/htdocs/
