name: Eleventy Build
on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      - run: npm ci
      - run: npm run scss
      - run: npm run build --if-present
      - name: push action to dist
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.TOKEN_GIT }}
          directory: dist

      - name: Upload build to hosting environment
        uses: Creepios/sftp-action@v1.0.1
        with:
          host: ${{ secrets.FTP_SERVER }}
          port: 22
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          localPath: './dist'
          remotePath: './lamp0/web/vhosts/crm.6337.fr/htdocs'
